@startuml
left to right direction

' CAPAS DEL SISTEMA -----------------------------------

package "Capa Negocio"{
    class GestorGranja {
        - parcelas : ArrayList<Parcela>
        - aspersoresInventario : ArrayList<Aspersor>
        - sensoresInventario : ArrayList<SensorHumedad>
        - gestorParcelas : GestorParcelas
        - gestorAspersores : GestorAspersores
        - gestorSensores : GestorSensores
        - gestorCultivos : GestorCultivos
        - gestorArduino : GestorArduino
        - gestorUsuarios : GestorUsuarios
        - contadorIdAspersores : int
        - contadorIdSensores : int
        - operacionesCrud : OperacionesCrud

        + GestorGranja()
        + setPersistenciaService(operacionesCrud : OperacionesCrud) : void
        + getPersistenciaService() : OperacionesCrud
        + getParcelas() : ArrayList<Parcela>
        + setParcelas(parcelas : ArrayList<Parcela>) : void
        + getAspersoresInventario() : ArrayList<Aspersor>
        + setAspersoresInventario(aspersoresInventario : ArrayList<Aspersor>) : void
        + getSensoresInventario() : ArrayList<SensorHumedad>
        + setSensoresInventario(sensoresInventario : ArrayList<SensorHumedad>) : void
        + getGestorParcelas() : GestorParcelas
        + getGestorAspersores() : GestorAspersores
        + getGestorSensores() : GestorSensores
        + getGestorCultivos() : GestorCultivos
        + getGestorArduino() : GestorArduino
        + getGestorUsuarios() : GestorUsuarios
        + getSiguienteIdAspersor() : String
        + getSiguienteIdSensor() : String
        + getContadorIdAspersores() : int
        + incrementarContadorAspersores() : void
        + getContadorIdSensores() : int
        + incrementarContadorSensores() : void
    }

    class GestorParcelas {
        - gestorGranja : GestorGranja
        - contadorParcelas : int
        - operacionesCrud : OperacionesCrud

        + GestorParcelas(gestorGranja : GestorGranja)
        + setPersistenciaService(operacionesCrud : OperacionesCrud) : void
        + crearParcelas(terrenoTotal : double) : void
        - asignarDispositivosAutomaticamente() : void
        + mostrarInformacionParcelas() : void
        + eliminarParcela(idParcela : String) : void
        + buscarParcela(idParcela : String) : Parcela
    }

    class GestorAspersores {
        - gestorGranja : GestorGranja
        - operacionesCrud : OperacionesCrud

        + GestorAspersores(gestorGranja : GestorGranja)
        + setPersistenciaService(operacionesCrud : OperacionesCrud) : void
        + agregarAspersoresInventario(cantidad : int) : void
        + mostrarInformacionAspersores() : void
        + asignarAspersorAParcela(idParcela : String) : void
        + asignarAspersorEspecificoAParcela(idAspersor : String, idParcela : String) : void
        + prenderManualmente(idAspersor : String) : void
        + realizarRiegoAutomatico() : void
        + conectarDesconectarAspersor(idAspersor : String) : void
        + mostrarHistorialAspersor(idAspersor : String) : void
        + eliminarAspersor(idAspersor : String) : void
        + buscarAspersor(idAspersor : String) : Aspersor
    }

    class GestorSensores {
        - gestorGranja : GestorGranja
        - operacionesCrud : OperacionesCrud

        + GestorSensores(gestorGranja : GestorGranja)
        + setPersistenciaService(operacionesCrud : OperacionesCrud) : void
        + agregarSensoresInventario(cantidad : int) : void
        + mostrarInformacionSensores() : void
        + asignarSensorAParcela(idParcela : String) : void
        + asignarSensorEspecificoAParcela(idSensor : String, idParcela : String) : void
        + conectarDesconectarSensor(idSensor : String) : void
        + simularLecturasTodasParcelas() : void
        + mostrarLecturasSensor(idSensor : String) : void
        + eliminarSensor(idSensor : String) : void
        + buscarSensor(idSensor : String) : SensorHumedad
    }

    class GestorCultivos {
        - gestorGranja : GestorGranja
        - cultivosDisponibles : ArrayList<Cultivo>
        - operacionesCrud : OperacionesCrud

        + GestorCultivos(gestorGranja : GestorGranja)
        + setPersistenciaService(operacionesCrud : OperacionesCrud) : void
        - inicializarCultivos() : void
        + mostrarCultivosDisponibles() : void
        + registrarCultivoEnParcela(idParcela : String, nombreCultivo : String) : void
        + cambiarCultivoParcela(idParcela : String, nombreCultivo : String) : void
        - buscarCultivo(nombre : String) : Cultivo
        + getCultivosDisponibles() : ArrayList<Cultivo>
    }

    class GestorUsuarios {
        - gestorGranja : GestorGranja
        - usuarios : ArrayList<Usuario>
        - usuarioActual : Usuario
        - contadorUsuarios : int
        - operacionesCrud : OperacionesCrud

        + GestorUsuarios(gestorGranja : GestorGranja)
        + GestorUsuarios()
        + setPersistenciaService(operacionesCrud : OperacionesCrud) : void
        - cargarUsuariosDesdeDB() : void
        - inicializarUsuariosPorDefecto() : void
        + agregarUsuario(nombre : String, apellido : String, email : String, telefono : String, rol : String) : boolean
        + seleccionarUsuarioActual(idUsuario : String) : void
        + mostrarUsuarios() : void
        + editarUsuario(idUsuario : String, nombre : String, apellido : String, email : String, telefono : String, rol : String) : void
        + desactivarUsuario(idUsuario : String) : void
        + activarUsuario(idUsuario : String) : void
        + buscarUsuario(idUsuario : String) : Usuario
        + getUsuarios() : ArrayList<Usuario>
        + getUsuariosActivos() : ArrayList<Usuario>
        + getUsuarioActual() : Usuario
        + setUsuarioActual(usuarioActual : Usuario) : void
        + cerrarSesion() : void
    }
}
package "Capa Controlador"{
    class GranjaControlador {
        - gestorGranja : GestorGranja
        - operacionesCrud : OperacionesCrud

        + GranjaControlador(gestorGranja : GestorGranja, operacionesCrud : OperacionesCrud)
        + obtenerUsuarios() : ArrayList<Usuario>
        + obtenerUsuariosActivos() : ArrayList<Usuario>
        + seleccionarUsuarioActual(idUsuario : String) : void
        + obtenerUsuarioActual() : Usuario
        + agregarUsuario(nombre : String, apellido : String, email : String, telefono : String, rol : String) : boolean
        + cerrarSesionUsuario() : void
        + crearParcelas(terrenoTotal : double) : void
        + obtenerParcelas() : ArrayList<Parcela>
        + obtenerAspersoresInventario() : ArrayList<Aspersor>
        + obtenerSensoresInventario() : ArrayList<SensorHumedad>
        + obtenerTodosAspersores() : ArrayList<Aspersor>
        + obtenerTodosSensores() : ArrayList<SensorHumedad>
        + agregarAspersoresInventario(cantidad : int) : void
        + agregarSensoresInventario(cantidad : int) : void
        + asignarAspersorAParcela(idParcela : String) : void
        + asignarAspersorEspecificoAParcela(idAspersor : String, idParcela : String) : void
        + asignarSensorAParcela(idParcela : String) : void
        + asignarSensorEspecificoAParcela(idSensor : String, idParcela : String) : void
        + obtenerCultivosDisponibles() : ArrayList<Cultivo>
        + registrarCultivoEnParcela(idParcela : String, nombreCultivo : String) : void
        + cambiarCultivoParcela(idParcela : String, nombreCultivo : String) : void
        + eliminarParcela(idParcela : String) : void
        + simularLecturasYRiego() : void
        + prenderAspersorManualmente(idAspersor : String) : void
        + conectarDesconectarAspersor(idAspersor : String) : void
        + conectarDesconectarSensor(idSensor : String) : void
        + eliminarAspersor(idAspersor : String) : void
        + eliminarSensor(idSensor : String) : void
        + buscarParcela(idParcela : String) : Parcela
    }
}
package "Capa Interfaz"{
    class VentanaComandos implements CommandLineRunner {
        ' Spring Boot necesita una forma de ejecutar código automáticamente al iniciar la aplicación
        - gestorGranja : GestorGranja
        - operacionesCrud : OperacionesCrud
        - scanner : Scanner {static}
        ' Permite leer datos que el usuario escribe por teclado
        ' final para que detecte automaticamente y lo inyecte y no se va a modificar, si no estuviera el final no se ejecuta

        + main(args : String[]) : void
        + run(args : String[]) : void
        - inicializarSistema() : void
        - ejecutarMenuPrincipal() : void
        - opcionAnadirTerreno() : void
        - opcionAsignarAspersor() : void
        - opcionAsignarSensor() : void
        - opcionAgregarAspersores() : void
        - opcionAgregarSensores() : void
        - opcionRegistrarCultivo() : void
        - opcionEliminarParcela() : void
        - opcionCambiarCultivo() : void
        - opcionRiegoAutomatico() : void
        - opcionMostrarLecturasSensor() : void
        - opcionMostrarHistorialAspersor() : void
        - opcionPrenderAspersor() : void
        - opcionConectarDesconectarAspersor() : void
        - opcionConectarDesconectarSensor() : void
        - opcionEliminarAspersor() : void
        - opcionEliminarSensor() : void
        - opcionEscanearArduinos() : void
        - opcionRegistrarSensorArduino() : void
        - opcionRegistrarAspersorArduino() : void
        - opcionMostrarDispositivosArduino() : void
        - opcionSeleccionarUsuario() : void
        - opcionAgregarUsuario() : void
    }

    class VistaPrincipal extends VerticalLayout {
        'Es un componente visual contenedor.

        - controller : GranjaControlador
        - contentLayout : VerticalLayout
        - userBar : HorizontalLayout

        + VistaPrincipal(controller : GranjaControlador)
        - createUserBar() : HorizontalLayout
        - actualizarBarraUsuario() : void
        - createTabs() : Tabs
        - mostrarVistaUsuarios() : void
        - mostrarVistaParcelas() : void
        - mostrarVistaAspersores() : void
        - mostrarVistaSensores() : void
        - mostrarVistaCultivos() : void
        - mostrarVistaRiego() : void
        - actualizarGridParcelas() : void
        - actualizarGridAspersores() : void
        - actualizarGridSensores() : void
        - actualizarGridRiego() : void
        - actualizarVistaUsuarios() : void
        - mostrarNotificacion(mensaje : String, variant : NotificationVariant) : void
        - mostrarDialogoConfirmacion(mensaje : String, onConfirm : Runnable) : void
    }
}
package "Capa Modelo"{
    class Usuario {
        - id : String
        - nombre : String
        - apellido : String
        - email : String
        - telefono : String
        - rol : String
        - fechaRegistro : LocalDateTime
        - activo : boolean

        + Usuario(id : String, nombre : String, apellido : String, email : String, telefono : String, rol : String)
        + getId() : String
        + setId(id : String) : void
        + getNombre() : String
        + setNombre(nombre : String) : void
        + getApellido() : String
        + setApellido(apellido : String) : void
        + getEmail() : String
        + setEmail(email : String) : void
        + getTelefono() : String
        + setTelefono(telefono : String) : void
        + getRol() : String
        + setRol(rol : String) : void
        + getFechaRegistro() : LocalDateTime
        + setFechaRegistro(fechaRegistro : LocalDateTime) : void
        + isActivo() : boolean
        + setActivo(activo : boolean) : void
        + getNombreCompleto() : String
        + toString() : String
    }

    class Parcela {
        - id : String
        - metrosCuadrados : double
        - cultivo : Cultivo
        - aspersores : ArrayList<Aspersor>
        - sensores : ArrayList<SensorHumedad>
        - usuarioCreador : Usuario
        - fechaCreacion : LocalDateTime

        + Parcela(id : String, metrosCuadrados : double)
        + getId() : String
        + setId(id : String) : void
        + getMetrosCuadrados() : double
        + setMetrosCuadrados(metrosCuadrados : double) : void
        + getCultivo() : Cultivo
        + setCultivo(cultivo : Cultivo) : void
        + getAspersores() : ArrayList<Aspersor>
        + setAspersores(aspersores : ArrayList<Aspersor>) : void
        + getSensores() : ArrayList<SensorHumedad>
        + setSensores(sensores : ArrayList<SensorHumedad>) : void
        + getUsuarioCreador() : Usuario
        + setUsuarioCreador(usuarioCreador : Usuario) : void
        + getFechaCreacion() : LocalDateTime
        + setFechaCreacion(fechaCreacion : LocalDateTime) : void
        + agregarAspersor(aspersor : Aspersor) : void
        + agregarSensor(sensor : SensorHumedad) : void
        + removerAspersor(aspersor : Aspersor) : void
        + removerSensor(sensor : SensorHumedad) : void
        + toString() : String
    }

    class Aspersor {
        - id : String
        - conectado : boolean
        - encendido : boolean
        - parcela : Parcela
        - historialEncendidos : ArrayList<LocalDateTime>

        + Aspersor(id : String)
        + getId() : String
        + setId(id : String) : void
        + isConectado() : boolean
        + setConectado(conectado : boolean) : void
        + isEncendido() : boolean
        + setEncendido(encendido : boolean) : void
        + getParcela() : Parcela
        + setParcela(parcela : Parcela) : void
        + getHistorialEncendidos() : ArrayList<LocalDateTime>
        + setHistorialEncendidos(historialEncendidos : ArrayList<LocalDateTime>) : void
        + registrarEncendido() : void
        + encender() : void
        + apagar() : void
        + toString() : String
    }

    class SensorHumedad {
        - id : String
        - conectado : boolean
        - humedadActual : int
        - parcela : Parcela
        - lecturas : ArrayList<LecturaHumedad>

        + SensorHumedad(id : String)
        + getId() : String
        + setId(id : String) : void
        + isConectado() : boolean
        + setConectado(conectado : boolean) : void
        + getHumedadActual() : int
        + setHumedadActual(humedadActual : int) : void
        + getParcela() : Parcela
        + setParcela(parcela : Parcela) : void
        + getLecturas() : ArrayList<LecturaHumedad>
        + setLecturas(lecturas : ArrayList<LecturaHumedad>) : void
        + realizarLectura() : void
        + toString() : String
    }

    class Cultivo {
        - nombre : String
        - humedadMinima : int
        - humedadMaxima : int
        - frecuenciaRiegoHoras : int

        + Cultivo(nombre : String, humedadMinima : int, humedadMaxima : int, frecuenciaRiegoHoras : int)
        + getNombre() : String
        + setNombre(nombre : String) : void
        + getHumedadMinima() : int
        + setHumedadMinima(humedadMinima : int) : void
        + getHumedadMaxima() : int
        + setHumedadMaxima(humedadMaxima : int) : void
        + getFrecuenciaRiegoHoras() : int
        + setFrecuenciaRiegoHoras(frecuenciaRiegoHoras : int) : void
        + toString() : String
    }

    class LecturaHumedad {

        - fecha : LocalDateTime
        - porcentajeHumedad : int

        + LecturaHumedad(fecha : LocalDateTime, porcentajeHumedad : int)
        + getFecha() : LocalDateTime
        + setFecha(fecha : LocalDateTime) : void
        + getPorcentajeHumedad() : int
        + setPorcentajeHumedad(porcentajeHumedad : int) : void
        + toString() : String
    }
}
package "Capa Servicio / Persistencia"{
    class OperacionesCrud {

        - usuarioRepositorio : UsuarioRepositorio
        - parcelaRepositorio : ParcelaRepositorio
        - aspersorRepositorio : AspersorRepositorio
        - sensorRepository : SensorHumedadRepositorio
        - cultivoRepositorio : CultivoRepositorio
        - lecturaRepository : LecturaHumedadRepositorio
        - historialRepository : HistorialEncendidoRepositorio

        + buscarPorEmailActivo (email : String) : boolean
        + guardarUsuario(usuario : Usuario) : void
        + cargarUsuarios() : List<Usuario>
        + guardarParcela(parcela : Parcela, usuario : Usuario) : void
        + eliminarParcela(idParcela : String) : void
        + guardarAspersor(aspersor : Aspersor) : void
        + eliminarAspersor(idAspersor : String) : void
        + guardarSensor(sensor : SensorHumedad) : void
        + eliminarSensor(idSensor : String) : void
        + guardarLecturaHumedad(sensorId : String, lectura : LecturaHumedad) : void
        + guardarHistorialEncendido(aspersorId : String, fecha : java.time.LocalDateTime) : void
        + inicializarCultivos() : void
        + actualizarCultivoParcela(idParcela : String, nombreCultivo : String) : void
    }
}

' RELACIONES – CAPA NEGOCIO -----------------------------------
'Composición
'GestorGranja posee y administra parcelas, aspersores y sensores
'Si la granja deja de existir, estos elementos no tienen sentido sin ella
GestorGranja "1" *-- "many" Parcela
GestorGranja "1" *-- "many" Aspersor
GestorGranja "1" *-- "many" SensorHumedad

'Composición
'GestorGranja crea y controla los gestores
'Los gestores no existen de forma independiente
GestorGranja "1" *-- GestorParcelas
GestorGranja "1" *-- GestorAspersores
GestorGranja "1" *-- GestorSensores
GestorGranja "1" *-- GestorCultivos
GestorGranja "1" *-- GestorUsuarios

'Asociación dirigida
'Cada gestor necesita consultar o modificar el estado global de la granja
'No la posee, solo la usa
GestorParcelas --> GestorGranja
GestorAspersores --> GestorGranja
GestorSensores --> GestorGranja
GestorCultivos --> GestorGranja
GestorUsuarios --> GestorGranja

'Dependencia / asociación
'Los gestores guardan, eliminan y consultan datos
'No crean el servicio, solo lo usan
GestorParcelas --> OperacionesCrud
GestorAspersores --> OperacionesCrud
GestorSensores --> OperacionesCrud
GestorCultivos --> OperacionesCrud
GestorUsuarios --> OperacionesCrud
GestorGranja --> OperacionesCrud

' RELACIONES – CAPA CONTROLADOR -----------------------------------

'Asociación
'Orquesta casos de uso
'No contiene lógica de negocio profunda
'Solo delega
GranjaControlador --> GestorGranja
GranjaControlador --> OperacionesCrud

' RELACIONES – CAPA INTERFAZ -----------------------------------

'Asociación
'La consola se comuncia directamente con el negocio
'No necesita controlador intermedio
VentanaComandos --> GestorGranja
VentanaComandos --> OperacionesCrud
'La vista habla con el controlador
VistaPrincipal --> GranjaControlador
'Respeta MVC (MODELO-VISTA-CONTROLADOR)

' RELACIONES – CAPA MODELO -----------------------------------

'Agregacion
'Un aspersor/sensor puede existir sin parcela
'Pero cuando se asigna, pertenece a ella
Parcela "1" o-- "0..*" Aspersor
Parcela "1" o-- "0..*" SensorHumedad

'Asociacion
'Una parcela tiene un cultivo
'Fue creada por un usuario
Parcela "1" --> "1" Cultivo
Parcela "1" --> "1" Usuario

'Asociación
'Conocen a cual estan asginados
Aspersor --> Parcela
SensorHumedad --> Parcela

'Composición
'Una lectura no existe sin su sensor
'Se elimina el sensor se eliminan lecturas
SensorHumedad "1" *-- "many" LecturaHumedad

' RELACIONES – PERSISTENCIA -----------------------------------

'Asociación
'Guarda/Elimina/Actualiza
OperacionesCrud --> Usuario
OperacionesCrud --> Parcela
OperacionesCrud --> Aspersor
OperacionesCrud --> SensorHumedad
OperacionesCrud --> Cultivo
OperacionesCrud --> LecturaHumedad
@enduml